use_frameworks!

target 'PodLearn_Example' do
  pod 'PodLearn', :path => '../'

  target 'PodLearn_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
